var PublicSequence = React.createClass({

  getInitialState: function() {
      return { asanas: this.props.initialAsanas };
  },

  render: function() {
    var asanas = this.state.asanas.map(function(asana) {
      return <Asana key={asana.id} asana={asana} />;
    })
    return (
      <div className="asanas">
        {asanas}
      </div>
    );
  },

});

var SequenceSelector = React.createClass({

  getInitialState: function() {
      return { 
        asanas: this.props.initialAsanas,
      };
  },

  render: function() {
    var asanas = this.state.asanas.map(function(asana) {
      return <Asana key={asana.id} asana={asana} />;
    })

    return (
      <div>
        <h3>Asana Reference</h3>
        <div className="asanas">
          {asanas}
        </div>
      </div>
    );
  }

})

var SequenceSorter = React.createClass({

  // getInitialState: function() {
  //   // return {
  //     // seqAsanas: this.props.initialAsanas,
  //     //   seqAsanasOrder: whatever is autogenerated (right now IDs)
  //     // seqId
  //   }
  // },


  componentDidMount: function() {
    $("#sequence_asanas").sortable();

  //   $(".save-order").on("click", function() {
  //     var lengthOfSeq = $(".seq-card").length
  //     var cardNamesInOrder = []
  //     var seqId = $(".hidden-id").text()
  //     var url = seqId + ".json"
  //     for (var i = 0; i < lengthOfSeq; i++) {
  //       var seqId = $(".seq-card").eq(i).find($(".seq-order-id")).text();
  //       cardNamesInOrder.push(seqId);
  //     }
  //     $.ajax({
  //       url: url,
  //       type: "get",
  //       dataType: "json"
  //     }).done(function(response){
  //       console.log(response)
  //     }).fail(function(){
  //       console.log("Ajax request fails!")
  //     })
  // })
  },



  render: function() {
    return (
     
     <p></p>
      // <button className="save-order">Save</button>
      );
  }

})

var AsanaSearch = React.createClass({

  componentDidMount: function() {
    $('#search').hideseek();
  },

  render: function() {
    return (
    <p>
      <input id="search" name="search" placeholder="Search" type="text" data-toggle="hideseek" data-list=".searchable" />
    </p>
    );
  }

})